<!-- Ambil data dari data.json -->
<?php
$data = json_decode(file_get_contents('data.json'), true);
?>
<!-- //Ambil data dari data.json -->

<div class="w-full overflow-x-auto">

	<!-- Table -->
    <table class="w-full table-auto">
        <thead>
            <tr class="bg-emerald-50 text-left">
                <th class="border px-4 py-2">ID</th>
                <th class="border px-4 py-2">Nama</th>
                <th class="border px-4 py-2">Harga</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($data as $item): ?>
                <tr class="bg-white">
					
					<!-- Tampilkan data dari data.json -->
                    <td class="border px-4 py-2"><?php echo $item['id']; ?></td>
                    <td class="border px-4 py-2"><?php echo $item['name']; ?></td>
                    <td class="border px-4 py-2"><?php echo $item['price']; ?></td>
					<!-- //Tampilkan data dari data.json -->
					
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
	<!-- //Table -->
	
</div>
